version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db_basamento
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_basamento
      MYSQL_USER: user_basamento
      MYSQL_PASSWORD: root
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3308:3306"
